### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by yuvalkirstain** [jjihwan/FIFO-Diffusion_public#1]
Hey, congrats on the paper! It seems like the readme mentions files that are missing. Any plans to release code?

**Comment by jjihwan** [comment]
Thank you for interest in our research. We are actually planning to release all the source codes, but we don't have a specific timeline for that yet 😅

**Comment by howardgriffin** [comment]
Waiting for the code!

**Comment by zhanghongyong123456** [comment]
> 感谢您对我们的研究感兴趣。我们实际上计划发布所有源代码，但我们还没有具体的时间表 😅



> Thank you for interest in our research. We are actually planning to release all the source codes, but we don't have a specific timeline for that yet 😅

+1

**Comment by Edwardmark** [comment]
Waiting for the code!

**Comment by jjihwan** [comment]
We will release our code soon, possibly in a few days..!

**Comment by cuijh26** [comment]
wonderful！So great work!

**Comment by jjihwan** [comment]
The code has been released!
