### ISSUE TITLE
MP4 fps locked to 10

### ISSUE THREAD

**Issue by SoftologyPro** [jjihwan/FIFO-Diffusion_public#10]
Shouldn't this line
`            imageio.mimsave(output_path+".mp4", video_frames[-args.new_video_length:], fps=10)`
be
`            imageio.mimsave(output_path+".mp4", video_frames[-args.new_video_length:], fps=args.fps)`

**Comment by jjihwan** [comment]
`args.fps` is the argument injected as the model input, not the fps of the saved video. You can add `--output_fps` if you want to control the output fps

**Comment by SoftologyPro** [comment]
I don't see the `--output_fps` parameter and the mp4 fps is still hard coded to 10?

**Comment by jjihwan** [comment]
Ah, I meant you can change the code to control it.
I'm going to make the change for you soon, lol.

**Comment by SoftologyPro** [comment]
Thank you.  I know I can make the change, but I am adding support for FIFO-Diffusion in Visions of Chaos https://softology.pro/voc.htm so users will be checking out the repo when they get the latest scripts.  I could write a bunch of code to auto-edit changes in for them, but it is simpler if you do it with the master repo code.  With the output fps option that should cover all issues.

**Comment by jjihwan** [comment]
Oh I see. Thank you for your effort! :) I've just committed the changes.
