### ISSUE TITLE
Missing inferenceT2v_512_v2.0.yaml file

### ISSUE THREAD

**Issue by mikeyimer** [jjihwan/FIFO-Diffusion_public#12]
missing configs\inferenceT2v_512_v2.0.yaml file,it seems that this file is not in configs
![af](https://github.com/jjihwan/FIFO-Diffusion_public/assets/137673481/1310b794-948e-465e-839c-c1c89aa7b9dc)

**Comment by jjihwan** [comment]
OMG, sorry :(
I mistakenly removed the config files, but I have just added them back. Thank you for the report!
