### ISSUE TITLE
No module named 'omegaconf'

### ISSUE THREAD

**Issue by johnFreddie** [jjihwan/FIFO-Diffusion_public#16]
When I run python3 videocrafter_main.py --save_frames there is a error shows that No module named 'omegaconf'. i make sure i have installed omegaconf

**Comment by jjihwan** [comment]
Did you create the conda environment following our README?
It seems to work well on my machine tho.
Plz inform me if you resolve the issue.

**Comment by johnFreddie** [comment]
> Did you create the conda environment following our README? It seems to work well on my machine tho. Plz inform me if you resolve the issue.

I had created the environment, and  env name is fifo, maybe the error is happened in 'python3 videocrafter_main.py --save_frames',because I can use run 'videocrafter_main.py' by vscode.
