### ISSUE TITLE
Multi-prompts generation

### ISSUE THREAD

**Issue by o0o0o00o0** [jjihwan/FIFO-Diffusion_public#19]
I used three prompt words, but there was no transition between the three videos, as shown in the paper. What should I do?

**Comment by prajwalsingh** [comment]
Hi @o0o0o00o0 , check this [[link](https://github.com/jjihwan/FIFO-Diffusion_public/issues/22)]. With this fix I am able to generate multi-prompt videos.

**Comment by jjihwan** [comment]
@prajwalsingh Thank you!
