### ISSUE TITLE
open_clip_torch v2.26.0 causes RTE with FIFODiffusion

### ISSUE THREAD

**Issue by a-r-r-o-w** [jjihwan/FIFO-Diffusion_public#25]
Just a notification but the latest release of open_clip_torch (v2.26.0) causes a RuntimeError when running inference. Reverting back to v2.24.0 fixes this. It would be good to set `open_clip_torch<=2.24.0` in requirements.txt, and might help others trying this out

**Comment by jjihwan** [comment]
Got it, Thanks!
