### ISSUE TITLE
confusion between the code and the paper

### ISSUE THREAD

**Issue by yuzhi535** [jjihwan/FIFO-Diffusion_public#26]
https://github.com/jjihwan/FIFO-Diffusion_public/blob/4ef71d4d89b578e5d2f6c9c8c108ab45b5738baf/scripts/evaluation/funcs.py#L207

Hi author, I don't quite understand why the reverse operation is done here.  It seems Algorithms 2 and 3 do not indicate this operation. So what does this reverse mean?

**Comment by jjihwan** [comment]
The `reversed` operation is used to directly update the queue without using additional memory (or variable) when performing lookahead denoising.
Without `reversed`, you would need to save the last half frames of each queue into another variable to achieve lookahead denoising.
We didn't include it in the paper for better clarity.

**Comment by yuzhi535** [comment]
Ok, i understand the explanation. Thanks for your patience.
