### ISSUE TITLE
user input initial frames

### ISSUE THREAD

**Issue by ZhangT-tech** [jjihwan/FIFO-Diffusion_public#27]
Hi, 

Thanks for the great work done. I am exploring the code base, and I wonder how it can use user input frames as a condition, rather than the generated frames by videocrafter or sora-plan.

**Comment by jjihwan** [comment]
Hey,
For VC2, you can try to replace [here](https://github.com/jjihwan/FIFO-Diffusion_public/blob/4ef71d4d89b578e5d2f6c9c8c108ab45b5738baf/scripts/evaluation/funcs_mp.py#L19) as your desired latents encoded by corresponding VAE.

**Comment by ZhangT-tech** [comment]
yes I tried with that, but it seems that the latents I input is not decoded in the right way, which doesn't show the original initial frames I input. I wonder where I can find how the model decode the latents, maybe that can solve my problem of inconsistent image decoding.

**Comment by jjihwan** [comment]
Ah, I see. Did you use proper encoder corresponding to the decoder?
You might have to use same encoder with what VC2 uses in training.

BTW, decoding code is [here](https://github.com/jjihwan/FIFO-Diffusion_public/blob/4ef71d4d89b578e5d2f6c9c8c108ab45b5738baf/scripts/evaluation/funcs_mp.py#L240).

**Comment by ZhangT-tech** [comment]
I see, could you tell me where to find the encoder VC2 uses in training?
Thank you a lot!

**Comment by jjihwan** [comment]
Honestly I don't know what they use, but I believe that you can find in VC2 original repo or technical report.
https://github.com/AILab-CVC/VideoCrafter
