### ISSUE TITLE
No Module called 'opensora.model.xxxxx'

### ISSUE THREAD

**Issue by ZhangT-tech** [jjihwan/FIFO-Diffusion_public#28]
Hi, thanks for your great work, I m trying with the open-sora-plan code following the Readme doc, but after installing everything, when i run the script opensora_fifo_65.sh, it shows me unable to load the module that is in Open-Sora-Plan. 

The directory now is:
FIFO-Diffusion-public /
--- Open-Sora-Plan /
------opensora /
---------model /
...............

**Comment by jjihwan** [comment]
Sry, i couldn't understand the issue
what is the exact error message ?

**Comment by ZhangT-tech** [comment]
Oh, thank you so much for your reply, the error message is like this:

(.sora) [zhant0g@gpu609-07 FIFO-Diffusion_public]$ sh ./scripts/opensora_fifo_65.sh 
************************************************** /ibex/user/zhant0g/code/FIFO-Diffusion_public/Open-Sora-Plan **************************************************
/ibex/user/zhant0g/code/FIFO-Diffusion_public/.sora/lib64/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/ibex/user/zhant0g/code/FIFO-Diffusion_public/.sora/lib64/python3.9/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
[2024-08-14 13:38:40,211] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The default cache directory for DeepSpeed Triton autotune, /home/zhant0g/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  NVIDIA Inference is only supported on Ampere and newer architectures
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
/ibex/user/zhant0g/code/FIFO-Diffusion_public/.sora/lib64/python3.9/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
/ibex/user/zhant0g/code/FIFO-Diffusion_public/.sora/lib64/python3.9/site-packages/diffusers/models/transformer_2d.py:20: FutureWarning: Transformer2DModelOutput is deprecated and will be removed in version 0.29. Importing Transformer2DModelOutput from diffusers.models.transformer_2d is deprecated and this will be removed in a future version. Please use from diffusers.models.transformers.transformer_2d import Transformer2DModelOutput, instead.
  deprecate("Transformer2DModelOutput", "0.29", deprecation_message)
/ibex/user/zhant0g/code/FIFO-Diffusion_public/.sora/lib64/python3.9/site-packages/diffusers/models/transformer_2d.py:25: FutureWarning: Transformer2DModel is deprecated and will be removed in version 0.29. Importing Transformer2DModel from diffusers.models.transformer_2d is deprecated and this will be removed in a future version. Please use from diffusers.models.transformers.transformer_2d import Transformer2DModel, instead.
  deprecate("Transformer2DModel", "0.29", deprecation_message)
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
Traceback (most recent call last):
  File "/ibex/user/zhant0g/code/FIFO-Diffusion_public/opensora_fifo/sample/sample_fifo.py", line 29, in <module>
    from opensora.models.ae import ae_stride_config, getae, getae_wrapper
ModuleNotFoundError: No module named 'opensora.models.ae'

I later I figure it out it's because I used the V1.2.0, rather than V1.1.0, which causes the module not found issue.
