### ISSUE TITLE
Is there an integrated way of combine FIFO pipeline into any other base t2v or i2v model?

### ISSUE THREAD

**Issue by ZhangT-tech** [jjihwan/FIFO-Diffusion_public#31]
Thanks for your great work!

I wonder if there is a way to integrate FIFO pipeline into any other base video generation model?
Is there a step to follow, or different integration for different diffusion model per se?

Best

**Comment by jjihwan** [comment]
Thank you for your interest.
Please refer to [this](https://github.com/jjihwan/FIFO-Diffusion_public/issues/11#issuecomment-2141290049)  for integration FIFO on other baselines.
