### ISSUE TITLE
MP4 rather than GIF

### ISSUE THREAD

**Issue by SoftologyPro** [jjihwan/FIFO-Diffusion_public#5]
Please save final movie as MP4 and not GIF.
GIF has reduced colors and color banding.

**Comment by SoftologyPro** [comment]
For anyone who wants to, replace line 102 in
`videocrafter_main.py`
from
`imageio.mimsave(output_dir+"/fifo.gif", video_frames[-args.new_video_length:], duration=100) `
to
`imageio.mimsave(output_dir+"/fifo.mp4", video_frames[-args.new_video_length:])`

**Comment by jjihwan** [comment]
You can now use "--use_mp4" option!
