### ISSUE TITLE
Suggestion for outputs

### ISSUE THREAD

**Issue by SoftologyPro** [jjihwan/FIFO-Diffusion_public#6]
1. Have an option for an output directory (outside the same directory as the py script).
2. Name the output file the same as the prompt.
3. Pararmeter to "only save final movie".  That automatically cleans up the extra unwanted files and allows the user to specify a directory of their choice for the final movie to save to.

Then (for example) I could easily have an output named
D:\Output\A colony of penguins waddling on an Antarctic ice sheet, 4K, ultra HD.mp4
All outputs then get a name to easily identify them and just the final movie is saved (which is what I think 99% of users would want).

**Comment by jjihwan** [comment]
Thank you for the suggestions!
We will address them soon.

**Comment by jjihwan** [comment]
@SoftologyPro  Your suggestions are now reflected as options:
- --save_frames: Store each frame as PNG (store_true argument).
- --use_mp4: Save movies as MP4 (store_true argument).
- --output_dir: Specify a custom output directory. The videos will be saved as you recommended.

**Comment by jjihwan** [comment]
@SoftologyPro  Your suggestions are now reflected as options:
- --save_frames: Store each frame as PNG (store_true argument).
- --use_mp4: Save movies as MP4 (store_true argument).
- --output_dir: Specify a custom output directory. The videos will be saved as you recommended.
