### ISSUE TITLE
Suggestion: Init Image and LORA Support

### ISSUE THREAD

**Issue by IIIIIIIllllllllIIIII** [jjihwan/FIFO-Diffusion_public#7]
I would like to suggest adding support for Init Image and LORA (Low-Rank Adaptation) in the txt2video AI tool. These features would enhance the tool’s flexibility and capability, allowing users to create more refined and controlled video outputs.

**Comment by jjihwan** [comment]
I totally agree, but I don't have enough time to implement them right now 🥲. Supporting LoRA, in particular, depends on the baseline model implementation, which in our case is VideoCrafter2. However, VC2 does not officially support LoRA yet. If you succeed in implementing it, we would welcome a pull request :)
